# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26162f5f3c671da2a45def8f7660351ddb4275e13632772caf3583fc2a485c416e50b4acce4a2610d9f6a050b3f7b0f0885dbe2365819179449ff9474ac261c4

test:
  secret_key_base: 34f6e45e9f3336f3551c066284567e6deb16f8665253e5c5df7358fd44b7001378a896e3b23f545162c36acbec0356e2b0c96df60d3d6def8201e6c3f029d6d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
